### ISSUE TITLE
The hitbox is not consistent with the actual size

### ISSUE THREAD

**Issue by linzexin022** [Globox1997/MobZ#14]
Hello there, I found the the hitbox of Yellow Slime is not consistent with the actual size.
![2020-07-19_14 03 57](https://user-images.githubusercontent.com/59003232/87868523-2a174900-c9c9-11ea-8e3e-c83533a71245.png)

**Comment by Globox1997** [comment]
thanks for the info, I´ll fix it

**Comment by Globox1997** [comment]
hopefully fixed in 2.4.3

**Comment by srnyx** [comment]
@linzexin022 This can be closed now
