### ISSUE TITLE
Information needed regarding Spawn Rates

### ISSUE THREAD

**Issue by BrekiTomasson** [Globox1997/MobZ#16]
First of all; big fan of the mod, it offers a much needed diversity that I've been missing in the game. I hope you continue to add more mobs to the list and possibly expand it with more "neutral" mobs that can spawn alongside sheep, cows, rabbits, fish etc. However, I'm a little bit confused over a couple of things in the configuration file. I might open more issues on this to keep it separate, so I'll just list the biggest one here:

The "Spawn rate" numbers all feel a bit arbitrary to me, as two different mobs set to the same number can be seen to spawn in very different amounts. Also, it's not entirely clear if a lower number means **more** spawns or **fewer** spawns. In fact, I seem to be getting roughly the same amount of Bowman spawns with the `BowmanSpawnRate` set to 1 or 15. What's the maximum number here? I see `SpeedyZombieSpawnRate` is set to 30 by default - is that the highest this goes? What effect can I expect if I set it to a much higher number, like 90? 150? 500? Some sort of documentation on the SpawnRate numbers is definitely in order.

**Comment by Globox1997** [comment]
thanks :D I´m not really working on this mod right now cause I have other plans. all of these mobs in this mod have vanilla models and I´m working on fully custom entities (adventurez mod). the spawn rate settings are the vanilla settings which is set from 0 to 100 (but you can increase it more). if I have time, I may add a description but it is in general not 100% clear (at least for me) how mc chooses which entity it will spawn
