### ISSUE TITLE
Updates beyond 1.16.1

### ISSUE THREAD

**Issue by BrekiTomasson** [Globox1997/MobZ#20]
Hello again! Now that the Fabric Biome Modification API is finalized, I'm hoping that we'll be seeing a 1.16.2, 1.16.3 and/or 1.16.4 version of this mod soon. It's one of only three mods that are holding me back from updating my server away from 1.16.1 right now. At this point, I honestly wouldn't mind losing the various mobs that this mod adds if it would allow me to upgrade the server, but so many people are wearing armor and/or weapons that this mod adds, so I'm stuck. 

Hope you can provide an upgrade soon! Thanks!

**Comment by Globox1997** [comment]
Hi Breki, haven't checked the api yet but I may do it soon. My intentional idea was to have separate mods for topics like mobs or weapons but I ignored that from time to time... This is one of my first mods and its kinda left behind + if you checked the code, it isn't really "clean" (as you like it xD) So I don't really plan to update it except for like 1.16.4 but it contains buggy and cheap code so... I would recommend to compensate the items from your server members and just remove the mod.

**Comment by BrekiTomasson** [comment]
Thanks for the info! Sad to see it go, but it's definitely understandable.

**Comment by rikka0w0** [comment]
Do you need any help in upgrading this mod? I really like the concept of this mod, very impressive. I could give it a go and fix some bugs that I encountered. Do you accept PR?

**Comment by Globox1997** [comment]
of course I accept PRs :D just not really motivated

**Comment by rikka0w0** [comment]
Okay, I spotted some issue. One of them is that, some mobs spawn underground (e.g. dwarf), but they extend the pillager class, once they join a raid, it will be so annoying to dig them out. I would like to make a change that, the only condition they can only the raid is that they must be able to see the sky.

I will submit a PR which fixes all of the game play problems and then start porting to 1.16.4

**Comment by Globox1997** [comment]
As I mentioned in another comment, it contains cheap code ^^ 
You can change whatever you like as you like :) 
Interesting that an electrical phd guy is modding for mc :D

**Comment by rikka0w0** [comment]
PR sent √

I started mc modding when I was a high school student(
Checkout my circuit and grid simulator mod:
https://github.com/RoyalAliceAcademyOfSciences/SimElectricity/tree/1.16.4

**Comment by rikka0w0** [comment]
[mobz-2.5.zip](https://github.com/Globox1997/MobZ/files/5905700/mobz-2.5.zip)

Update:
(Fix a spawning problem)
[mobz-2.5.1.zip](https://github.com/Globox1997/MobZ/files/5933970/mobz-2.5.1.zip)

Unofficial 1.16.4 release, rename to `.jar` and place into `mods` folder.

**Comment by PhillPhunny** [comment]
It's me, the guy from the CurseForge page, I renamed the file and then extracted it. After checking my Fabric loader and api (both were up-to-date, I then when to launch. No set up, instant crash, exit code:0, that happened the last time I extracted all the files then put them into the mods folder, so when I open the .zip it crashes and when I don't the launcher and loader won't even register. I'm almost positive that this is on my end, just looking to help in any way I can!
![Screenshot (2)](https://user-images.githubusercontent.com/78669821/107133977-6e116300-68b3-11eb-8fd8-0630c0886575.png)
![Screenshot (3)](https://user-images.githubusercontent.com/78669821/107133979-736ead80-68b3-11eb-8870-8949e777fd73.png)
***Also here are those useless screenshots!***
**Update: I used a .zip>.jar program, out of desperation, and it still didn't work. Crash, exit code:0**

**Comment by rikka0w0** [comment]
> It's me, the guy from the CurseForge page, I renamed the file and then extracted it. After checking my Fabric loader and api (both were up-to-date, I then when to launch. No set up, instant crash, exit code:0, that happened the last time I extracted all the files then put them into the mods folder, so when I open the .zip it crashes and when I don't the launcher and loader won't even register. I'm almost positive that this is on my end, just looking to help in any way I can!
> ![Screenshot (2)](https://user-images.githubusercontent.com/78669821/107133977-6e116300-68b3-11eb-8fd8-0630c0886575.png)
> ![Screenshot (3)](https://user-images.githubusercontent.com/78669821/107133979-736ead80-68b3-11eb-8870-8949e777fd73.png)
> _**Also here are those useless screenshots!**_
> **Update: I used a .zip>.jar program, out of desperation, and it still didn't work. Crash, exit code:0**

![image](https://user-images.githubusercontent.com/4704366/107149136-0fc7ab80-69ab-11eb-926d-6a1caaab1b5f.png)
Check this box in your explorer, and you will be able to see the file extensions (in this case, zip), change the .zip to .jar. Once you successfully change it, the icon will change as well.

**Comment by PhillPhunny** [comment]
> > It's me, the guy from the CurseForge page, I renamed the file and then extracted it. After checking my Fabric loader and api (both were up-to-date, I then when to launch. No set up, instant crash, exit code:0, that happened the last time I extracted all the files then put them into the mods folder, so when I open the .zip it crashes and when I don't the launcher and loader won't even register. I'm almost positive that this is on my end, just looking to help in any way I can!
> > ![Screenshot (2)](https://user-images.githubusercontent.com/78669821/107133977-6e116300-68b3-11eb-8fd8-0630c0886575.png)
> > ![Screenshot (3)](https://user-images.githubusercontent.com/78669821/107133979-736ead80-68b3-11eb-8870-8949e777fd73.png)
> > _**Also here are those useless screenshots!**_
> > **Update: I used a .zip>.jar program, out of desperation, and it still didn't work. Crash, exit code:0**
> 
> ![image](https://user-images.githubusercontent.com/4704366/107149136-0fc7ab80-69ab-11eb-926d-6a1caaab1b5f.png)
> Check this box in your explorer, and you will be able to see the file extensions (in this case, zip), change the .zip to .jar. Once you successfully change it, the icon will change as well.

It worked (you're a god of patience tyty) I'm thinking its some incompat, because it STILL will not load.

**Comment by Globox1997** [comment]
Updated on 1.16.5 by @rikka0w0
