### ISSUE TITLE
Fiora disables other aggressive mobs from spawning

### ISSUE THREAD

**Issue by DatrixTHLK** [Globox1997/MobZ#7]
Hi there,

During the time I played this Fiora shows up in mass quantities and steadily broke the aggressive mob spawning. Is there a way to take care of this? Or disable her at the very least? 

Minecraft: 1.15.1
Fabric Loader: 0.7.2+build.175
MobZ: 1.8.3

**Comment by Globox1997** [comment]
Should be fixed in 1.9.0
