### ISSUE TITLE
Admin Sword loot any user

### ISSUE THREAD

**Issue by perikitodestino** [Globox1997/MobZ#8]
Hello, today I noticed that a user of the server had the sword for administrators (with 2000 of damage). A mob had to loot it, which made me temporarily disable the mod to prevent it from happening again... Is it possible to avoid this in any way? Thanks

**Comment by Globox1997** [comment]
Which version do you play? It should be impossible to get the admin sword without creative gamemode or command rights because no entity has this sword in its loot table

**Comment by perikitodestino** [comment]
mc 1.15.1 with mobz 1.9.0... the person who had the sword was a normal user and told me that he got it by killing a mob... he didn't have the creative mode and can't execute commands because he's not a moderator... this person doesn't have the knowledge to use cheating...

but if you say it's not on the loot table, it's very, very strange... you make me wonder if any other option...

is it possible that I got into creative mode, I took that sword (I don't remember doing it but...), then I lost it, I took a mob and days later that normal user took it... haha it's a strange idea but I can't think of anything else!

i had deleted the mod, i'm going to put it back and keep testing... but can you think of anything with the information i gave you?

**Comment by perikitodestino** [comment]
I remembered that I put him in creative mode for 10 minutes once but the sword appeared days later... most likely my "friend" will have lied to me if you tell me that no entity has that sword on the loot table

I'm sorry for the inconvenience, I've activated the mod again and I'll keep an eye on what's going on these days...

I'm sorry and thank you very much for responding...

**Comment by Globox1997** [comment]
Please inform me if this appears again ;) The only thing I could do is to remove the admin sword at the next update
