### ISSUE TITLE
brownbear and boar2 spawns are broken, too many.

### ISSUE THREAD

**Issue by alertedpeak1748** [Globox1997/MobZ#9]
i have the 2.0.0 installed on the server and client and thats my error, are too many really too many mobs (the brokens are brownbear and boar2)   is any limitation method 4 the spawn?
![broken](https://user-images.githubusercontent.com/27936834/79060184-33ad4a00-7c3f-11ea-87ea-c336186df95e.png)

**Comment by Globox1997** [comment]
fixed in version 2.1.0
